import os
# On Windows, the path is incorrect, so change the path to
# the environment one. Even though windows is the problem,
# do it for all platforms
#SConscript('kkzpokerbot/SConscript')
newpath=os.environ.get('PATH')
env = Environment(ENV = { 'PATH' : newpath }, CCFLAGS='-std=c++11 -Ikkzpokerbot -Ikkzpokerbot/pokerstove')

libs = ['boost_program_options', 'boost_system', 'pthread']
env.Program('player', ['kkzpokerbot/main.cpp', 'kkzpokerbot/player.cpp', 'kkzpokerbot/libpeval.a'], LIBS=libs)
