import os
# On Windows, the path is incorrect, so change the path to
# the environment one. Even though windows is the problem,
# do it for all platforms
newpath=os.environ.get('PATH')
env = Environment(ENV = { 'PATH' : newpath }, CCFLAGS='-O3 -std=c++11')

boost_libs = ['boost_program_options', 'boost_system', 'pthread']
env.Program('player', ['main.cpp', 'player.cpp'], LIBS=boost_libs)
